-- Run this once in the Supabase SQL Editor (Dashboard -> SQL Editor -> New query)
-- before deploying. Creates the single table the whole app reads/writes.

create table if not exists items (
    url text primary key,
    title text not null,
    source text not null,
    tier integer not null,
    category text not null,
    published_at timestamptz,
    engagement_raw double precision default 0,
    summary text default '',
    is_builder_idea boolean default false,
    stack_tags text[] default '{}',
    dedup_key text default '',
    updated_at timestamptz default now()
);

-- Caches the on-demand AI summaries generated by /api/summary. Separate
-- table from items, since it's a different lifecycle (written once on
-- first request, read on every subsequent request for that URL).
create table if not exists summary_cache (
    url text primary key,
    summary text not null,
    created_at timestamptz default now()
);

-- Speeds up the filters the API actually uses (builder ideas tab, source
-- dropdown, sort by recency) -- without these, every /api/items call does
-- a full table scan once the table grows past a trivial size.
create index if not exists idx_items_published_at on items (published_at desc);
create index if not exists idx_items_is_builder_idea on items (is_builder_idea);
create index if not exists idx_items_source on items (source);

-- Required as of the 2026 Data API grants change: new projects need
-- explicit grants for PostgREST (the auto-generated REST API) to read/write
-- a table, rather than it being implicit. Run this even if your project
-- predates the change -- it's a no-op if access already works, and
-- required if it doesn't.
grant select, insert, update, delete on items to anon, authenticated, service_role;
grant select, insert, update, delete on summary_cache to anon, authenticated, service_role;

-- Row Level Security: ON, with one policy that allows anyone holding the
-- service_role key (used only by the backend and the GitHub Actions job,
-- never shipped to the frontend) full access. The anon key -- safe to use
-- in frontend code -- gets read-only.
alter table items enable row level security;
alter table summary_cache enable row level security;

create policy "service role full access" on items
    for all
    to service_role
    using (true)
    with check (true);

create policy "anon read access" on items
    for select
    to anon
    using (true);

create policy "service role full access" on summary_cache
    for all
    to service_role
    using (true)
    with check (true);

create policy "anon read access" on summary_cache
    for select
    to anon
    using (true);
